### PR TITLE
TAG Manager - data layer conversion data

### PR DESCRIPTION
**Pull request by rancey**
Hi Kristoff,

I am using the fooman TAG Manager code to send conversion tracking data to Facebook Tracking Pixel/Code..
To show the conversion data in FB, I need a dataLayer for GTM on the success page which contains the conversion data.  
This code adds this conversion data to the success page only - these dataLayer variables become available to GTM following this change:

conversion_order_id (order id of the converted order)
conversion_store (store name)
'conversion_revenue_excl_taxship (conversion value excluding tax and shipping)
conversion_revenue_shipping (conversion shipping revenue)
conversion_revenue_tax (conversion tax revenue)
conversion_revenue_revenue (total conversion value including tax and shipping)
conversion_currency  (currency code of the values)

It's does not affect the functionality of anything else within your code nor does it changes the way the GTM implementation works.

Regards,

Tim Rance
Corset Story Ltd.

### CODE REVIEW

**Comment by Flipmediaco** [comment]
Very useful and logical update.

**Comment by the2003s** [comment]
@fooman is this on the roadmap for the next release?

**Comment by phrench** [comment]
Another vote for this

**Comment by rmarji** [comment]
+1

**Comment by fooman** [comment]
Thanks Tim for adding this.

**Pull request merged**
