### PR TITLE
remove dublicate script tags in tagmanager template

### PR DESCRIPTION
**Pull request by steffen-wirth**
Tagmanager is not working now, we need to remove the dublicated script tags in tagmanger template file

### CODE REVIEW

**Comment by steffen-wirth** [comment]
@fooman i had no entry for the tag manager snippet in the backend, the problem is, that there where two script tags in the template conflicting
but i also realised later that, when the backend entry for the tagmanager is empty, there also need to be change in the observer checking this setting other wise the tagmanager template is not shown

**Comment by fooman** [comment]
@steffen-wirth thanks for the feedback. Can you check what changes would be needed with the latest release 0.18.3?

**Comment by steffen-wirth** [comment]
@fooman will have a look in the next days. shall i send you a new pull request with the changes?

**Comment by steffen-wirth** [comment]
@fooman i would also remove the not necessary config field for analyticsplus_tagmanager/snippet & the empty check for that field in the block class

**Comment by steffen-wirth** [comment]
Hi @fooman last week i had the time to work with v. 0.18.3 and the tagmanager seems fine, thx - i close this

**Pull request closed without merging**
